# BroadCasting

allows you to perform arithmetic operations on tensors with different shapes

In [1]:
import torch

/home/mtech1/miniconda3/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.tensor([2,3,4])
b = torch.tensor([5,6,7])

In [7]:
print(a)
print(a.shape)

tensor([2, 3, 4])
torch.Size([3])


In [9]:
print(b)
print(b.shape)

tensor([5, 6, 7])
torch.Size([3])


In [12]:
# Addition
c = a + b
print(c)
# both a and b are of same shape, this is element-wise addition
# same goes for substraction

tensor([ 7,  9, 11])


In [16]:
# How does these operations work for tensors with different shapes?
# Here broadcasting comes into play
# There are 3 different rules for broadcasting

In [17]:
tensor1 = torch.tensor([[1,2,3]]) # 1 x 3
tensor2 = torch.tensor([[4],[5],[6]]) # 3 x 1

In [18]:
print(tensor1.shape)
print(tensor2.shape)

torch.Size([1, 3])
torch.Size([3, 1])


In [21]:
# Not all tensors are broadcastable

In [22]:
# There is test that the tensors are broadcastable
# 1. Check tensors shapes from backward
#    We have (1,3) (3,1)
#    a) They are equal to each other or
#    b) one of the dimensions is one
#   What is the shape of the resulting tensor?
#   Take maximum from each dim ie, result = (3,3)

In [23]:
tensor1 + tensor2

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

In [47]:
a = torch.tensor([[1,2,3]]) # 1 x 3
b = torch.tensor(9) # scalar

In [48]:
a + b

tensor([[10, 11, 12]])

In [49]:
a * b

tensor([[ 9, 18, 27]])

In [50]:
# add 1 for the lower dimension tensor if there isn't a value
# associated with the higher dimension
# (8,7,6) 
# (5,4)
# add 1 to (5,4) in the last dimension to make proper comparision
# (8,7,6) and (5,4,1)